#!/usr/bin/env python3
"""Generate sample albums with proper ID3 tags for Rockbox simulator testing."""
import os
import shutil
from mutagen.id3 import ID3, TIT2, TPE1, TPE2, TALB, TRCK, TPOS, TDRC, TCON

SRC = os.path.expanduser("~/Temp/file_example_MP3_1MG.mp3")
DEST = os.path.expanduser("~/Source/rockbox/build-sim/simdisk/Music")

ALBUMS = [
    {
        "artist": "Sonic Youth",
        "album": "A Thousand Leaves",
        "year": "1998",
        "genre": "Alternative",
        "tracks": [
            "Contre le Sexisme",
            "Sunday",
            "Female Mechanic Now on Duty",
            "Wildflower Soul",
            "Hoarfrost",
            "French Tickler",
            "Hits of Sunshine",
            "Karen Koltrane",
            "The Ineffable Me",
            "Snare Girl",
            "Heather Angel",
            "Karen Revisited",
        ],
    },
    {
        "artist": "Radiohead",
        "album": "OK Computer",
        "year": "1997",
        "genre": "Alternative",
        "tracks": [
            "Airbag",
            "Paranoid Android",
            "Subterranean Homesick Alien",
            "Exit Music (For a Film)",
            "Let Down",
            "Karma Police",
            "Fitter Happier",
            "Electioneering",
            "Climbing Up the Walls",
            "No Surprises",
            "Lucky",
            "The Tourist",
        ],
    },
    {
        "artist": "Portishead",
        "album": "Dummy",
        "year": "1994",
        "genre": "Trip Hop",
        "tracks": [
            "Mysterons",
            "Sour Times",
            "Strangers",
            "It Could Be Sweet",
            "Wandering Star",
            "It's a Fire",
            "Numb",
            "Roads",
            "Pedestal",
            "Biscuit",
            "Glory Box",
        ],
    },
    {
        "artist": "Boards of Canada",
        "album": "Music Has the Right to Children",
        "year": "1998",
        "genre": "Electronic",
        "tracks": [
            "Wildlife Analysis",
            "An Eagle in Your Mind",
            "The Color of the Fire",
            "Telephasic Workshop",
            "Triangles & Rhombuses",
            "Sixtyten",
            "Turquoise Hexagon Sun",
            "Kaini Industries",
            "Bocuma",
            "Roygbiv",
            "Rue the Whirl",
            "Aquarius",
            "Olson",
            "Pete Standing Alone",
            "Smokes Quantity",
            "Open the Light",
            "One Very Important Thought",
            "Happy Cycling",
        ],
    },
    {
        "artist": "Massive Attack",
        "album": "Mezzanine",
        "year": "1998",
        "genre": "Trip Hop",
        "tracks": [
            "Angel",
            "Risingson",
            "Teardrop",
            "Inertia Creeps",
            "Exchange",
            "Dissolved Girl",
            "Man Next Door",
            "Black Milk",
            "Mezzanine",
            "Group Four",
            "(Exchange)",
        ],
    },
    {
        "artist": "My Bloody Valentine",
        "album": "Loveless",
        "year": "1991",
        "genre": "Shoegaze",
        "tracks": [
            "Only Shallow",
            "Loomer",
            "Touched",
            "To Here Knows When",
            "When You Sleep",
            "I Only Said",
            "Come in Alone",
            "Sometimes",
            "Blown a Wish",
            "What You Want",
            "Soon",
        ],
    },
    {
        "artist": "Aphex Twin",
        "album": "Selected Ambient Works 85-92",
        "year": "1992",
        "genre": "Electronic",
        "tracks": [
            "Xtal",
            "Tha",
            "Pulsewidth",
            "Ageispolis",
            "i",
            "Green Calx",
            "Heliosphan",
            "We Are the Music Makers",
            "Schottkey 7th Path",
            "Ptolemy",
            "Hedphelym",
            "Delphium",
            "Actium",
        ],
    },
    {
        "artist": "Bjork",
        "album": "Homogenic",
        "year": "1997",
        "genre": "Electronic",
        "tracks": [
            "Hunter",
            "Joga",
            "Unravel",
            "Bachelorette",
            "All Neon Like",
            "5 Years",
            "Immature",
            "Alarm Call",
            "Pluto",
            "All Is Full of Love",
        ],
    },
    {
        "artist": "Slowdive",
        "album": "Souvlaki",
        "year": "1993",
        "genre": "Shoegaze",
        "tracks": [
            "Alison",
            "Machine Gun",
            "40 Days",
            "Sing",
            "Here She Comes",
            "Souvlaki Space Station",
            "When the Sun Hits",
            "Altogether",
            "Melon Yellow",
            "Dagger",
        ],
    },
    {
        "artist": "Cocteau Twins",
        "album": "Heaven or Las Vegas",
        "year": "1990",
        "genre": "Dream Pop",
        "tracks": [
            "Cherry-Coloured Funk",
            "Pitch the Baby",
            "Iceblink Luck",
            "Fifty-Fifty Clown",
            "Heaven or Las Vegas",
            "I Wear Your Ring",
            "Fotzepolitic",
            "Wolf in the Breast",
            "Road, River and Rail",
            "Frou-Frou Foxes in Midsummer Fires",
        ],
    },
    {
        "artist": "Talk Talk",
        "album": "Spirit of Eden",
        "year": "1988",
        "genre": "Post-Rock",
        "tracks": [
            "The Rainbow",
            "Eden",
            "Desire",
            "Inheritance",
            "I Believe in You",
            "Wealth",
        ],
    },
    {
        "artist": "Mogwai",
        "album": "Young Team",
        "year": "1997",
        "genre": "Post-Rock",
        "tracks": [
            "Yes! I Am a Long Way from Home",
            "Like Herod",
            "Katrien",
            "Radar Maker",
            "Tracy",
            "Summer",
            "With Portfolio",
            "R U Still in 2 It",
            "A Cheery Wave from Stranded Youngsters",
            "Mogwai Fear Satan",
        ],
    },
    {
        "artist": "Stereolab",
        "album": "Dots and Loops",
        "year": "1997",
        "genre": "Post-Rock",
        "tracks": [
            "Brakhage",
            "Miss Modular",
            "The Flower Called Nowhere",
            "Diagonals",
            "Prisoner of Mars",
            "Rainbo Conversation",
            "Refractions in the Plastic Pulse",
            "Parsec",
            "Ticker-Tape of the Unconscious",
            "Contronatura",
        ],
    },
    {
        "artist": "Can",
        "album": "Future Days",
        "year": "1973",
        "genre": "Krautrock",
        "tracks": [
            "Future Days",
            "Spray",
            "Moonshake",
            "Bel Air",
        ],
    },
    {
        "artist": "Neu!",
        "album": "Neu!",
        "year": "1972",
        "genre": "Krautrock",
        "tracks": [
            "Hallogallo",
            "Sonderangebot",
            "Weissensee",
            "Im Gluck",
            "Negativland",
            "Lieber Honig",
        ],
    },
    {
        "artist": "The Smiths",
        "album": "The Queen Is Dead",
        "year": "1986",
        "genre": "Indie",
        "tracks": [
            "The Queen Is Dead",
            "Frankly, Mr. Shankly",
            "I Know It's Over",
            "Never Had No One Ever",
            "Cemetry Gates",
            "Bigmouth Strikes Again",
            "The Boy with the Thorn in His Side",
            "Vicar in a Tutu",
            "There Is a Light That Never Goes Out",
            "Some Girls Are Bigger Than Others",
        ],
    },
    {
        "artist": "Joy Division",
        "album": "Unknown Pleasures",
        "year": "1979",
        "genre": "Post-Punk",
        "tracks": [
            "Disorder",
            "Day of the Lords",
            "Candidate",
            "Insight",
            "New Dawn Fades",
            "She's Lost Control",
            "Shadowplay",
            "Wilderness",
            "Interzone",
            "I Remember Nothing",
        ],
    },
    {
        "artist": "Pixies",
        "album": "Doolittle",
        "year": "1989",
        "genre": "Alternative",
        "tracks": [
            "Debaser",
            "Tame",
            "Wave of Mutilation",
            "I Bleed",
            "Here Comes Your Man",
            "Dead",
            "Monkey Gone to Heaven",
            "Mr. Grieves",
            "Crackity Jones",
            "La La Love You",
            "No. 13 Baby",
            "There Goes My Gun",
            "Hey",
            "Silver",
            "Gouge Away",
        ],
    },
    {
        "artist": "Godspeed You! Black Emperor",
        "album": "Lift Your Skinny Fists Like Antennas to Heaven",
        "year": "2000",
        "genre": "Post-Rock",
        "tracks": [
            "Storm",
            "Static",
            "Sleep",
            "Antennas to Heaven",
        ],
    },
    {
        "artist": "Radiohead",
        "album": "Kid A",
        "year": "2000",
        "genre": "Electronic",
        "tracks": [
            "Everything in Its Right Place",
            "Kid A",
            "The National Anthem",
            "How to Disappear Completely",
            "Treefingers",
            "Optimistic",
            "In Limbo",
            "Idioteque",
            "Morning Bell",
            "Motion Picture Soundtrack",
        ],
    },
    {
        "artist": "Radiohead",
        "album": "In Rainbows",
        "year": "2007",
        "genre": "Alternative",
        "tracks": [
            "15 Step",
            "Bodysnatchers",
            "Nude",
            "Weird Fishes - Arpeggi",
            "All I Need",
            "Faust Arp",
            "Reckoner",
            "House of Cards",
            "Jigsaw Falling into Place",
            "Videotape",
        ],
    },
    {
        "artist": "Sonic Youth",
        "album": "Daydream Nation",
        "year": "1988",
        "genre": "Alternative",
        "tracks": [
            "Teen Age Riot",
            "Silver Rocket",
            "The Sprawl",
            "Cross the Breeze",
            "Eric's Trip",
            "Total Trash",
            "Hey Joni",
            "Providence",
            "Candle",
            "Rain King",
            "Kissability",
            "Trilogy: The Wonder",
            "Trilogy: Hyperstation",
            "Trilogy: Eliminator Jr.",
        ],
    },
    {
        "artist": "Massive Attack",
        "album": "Blue Lines",
        "year": "1991",
        "genre": "Trip Hop",
        "tracks": [
            "Safe from Harm",
            "One Love",
            "Blue Lines",
            "Be Thankful for What You've Got",
            "Five Man Army",
            "Unfinished Sympathy",
            "Daydreaming",
            "Lately",
            "Hymn of the Big Wheel",
        ],
    },
    {
        "artist": "Portishead",
        "album": "Third",
        "year": "2008",
        "genre": "Trip Hop",
        "tracks": [
            "Silence",
            "Hunter",
            "Nylon Smile",
            "The Rip",
            "Plastic",
            "We Carry On",
            "Deep Water",
            "Machine Gun",
            "Small",
            "Magic Doors",
            "Threads",
        ],
    },
    {
        "artist": "Boards of Canada",
        "album": "Geogaddi",
        "year": "2002",
        "genre": "Electronic",
        "tracks": [
            "Ready Lets Go",
            "Music Is Math",
            "Beware the Friendly Stranger",
            "Gyroscope",
            "Dandelion",
            "Sunshine Recorder",
            "In the Annex",
            "Julie and Candy",
            "The Smallest Weird Number",
            "1969",
            "Energy Warning",
            "The Beach at Redpoint",
            "Opening the Mouth",
            "Alpha and Omega",
            "I Saw Drones",
            "The Devil Is in the Details",
            "A Is to B as B Is to C",
            "Over the Horizon Radar",
            "Dawn Chorus",
            "Diving Station",
            "You Could Feel the Sky",
            "Corsair",
            "Magic Window",
        ],
    },
    {
        "artist": "Autechre",
        "album": "Tri Repetae",
        "year": "1995",
        "genre": "Electronic",
        "tracks": [
            "Dael",
            "Clipper",
            "Leterel",
            "Rotar",
            "Stud",
            "Eutow",
            "C-Pach",
            "Gnit",
            "Overand",
            "Rsdio",
        ],
    },
    {
        "artist": "Burial",
        "album": "Untrue",
        "year": "2007",
        "genre": "Electronic",
        "tracks": [
            "Untitled",
            "Archangel",
            "Near Dark",
            "Ghost Hardware",
            "Endorphin",
            "Etched Headplate",
            "In McDonalds",
            "Untrue",
            "Shell of Light",
            "Dog Shelter",
            "Homeless",
            "UK",
            "Raver",
        ],
    },
    {
        "artist": "Brian Eno",
        "album": "Ambient 1: Music for Airports",
        "year": "1978",
        "genre": "Ambient",
        "tracks": [
            "1/1",
            "2/1",
            "1/2",
            "2/2",
        ],
    },
    {
        "artist": "Brian Eno",
        "album": "Another Green World",
        "year": "1975",
        "genre": "Art Rock",
        "tracks": [
            "Sky Saw",
            "Over Fire Island",
            "St. Elmo's Fire",
            "In Dark Trees",
            "The Big Ship",
            "I'll Come Running",
            "Another Green World",
            "Sombre Reptiles",
            "Little Fishes",
            "Golden Hours",
            "Becalmed",
            "Zawinul/Lava",
            "Everything Merges with the Night",
            "Spirits Drifting",
        ],
    },
    {
        "artist": "Kraftwerk",
        "album": "Trans-Europe Express",
        "year": "1977",
        "genre": "Electronic",
        "tracks": [
            "Europe Endless",
            "The Hall of Mirrors",
            "Showroom Dummies",
            "Trans-Europe Express",
            "Metal on Metal",
            "Franz Schubert",
            "Endless Endless",
        ],
    },
    {
        "artist": "Kraftwerk",
        "album": "Computer World",
        "year": "1981",
        "genre": "Electronic",
        "tracks": [
            "Computer World",
            "Pocket Calculator",
            "Numbers",
            "Computer World 2",
            "Computer Love",
            "Home Computer",
            "It's More Fun to Compute",
        ],
    },
    {
        "artist": "The Cure",
        "album": "Disintegration",
        "year": "1989",
        "genre": "Post-Punk",
        "tracks": [
            "Plainsong",
            "Pictures of You",
            "Closedown",
            "Lovesong",
            "Last Dance",
            "Lullaby",
            "Fascination Street",
            "Prayers for Rain",
            "The Same Deep Water as You",
            "Disintegration",
            "Homesick",
            "Untitled",
        ],
    },
    {
        "artist": "Depeche Mode",
        "album": "Violator",
        "year": "1990",
        "genre": "Synth-Pop",
        "tracks": [
            "World in My Eyes",
            "Sweetest Perfection",
            "Personal Jesus",
            "Halo",
            "Waiting for the Night",
            "Enjoy the Silence",
            "Policy of Truth",
            "Blue Dress",
            "Clean",
        ],
    },
    {
        "artist": "New Order",
        "album": "Power, Corruption & Lies",
        "year": "1983",
        "genre": "Synth-Pop",
        "tracks": [
            "Age of Consent",
            "We All Stand",
            "The Village",
            "5 8 6",
            "Your Silent Face",
            "Ultraviolence",
            "Ecstasy",
            "Leave Me Alone",
        ],
    },
    {
        "artist": "Siouxsie and the Banshees",
        "album": "Juju",
        "year": "1981",
        "genre": "Post-Punk",
        "tracks": [
            "Spellbound",
            "Into the Light",
            "Arabian Knights",
            "Halloween",
            "Monitor",
            "Night Shift",
            "Sin in My Heart",
            "Head Cut",
            "Voodoo Dolly",
        ],
    },
    {
        "artist": "Wire",
        "album": "Pink Flag",
        "year": "1977",
        "genre": "Post-Punk",
        "tracks": [
            "Reuters",
            "Field Day for the Sundays",
            "Three Girl Rhumba",
            "Ex Lion Tamer",
            "Lowdown",
            "Start to Move",
            "Brazil",
            "It's So Obvious",
            "Surgeon's Girl",
            "Pink Flag",
            "The Commercial",
            "Straight Line",
            "106 Beats That",
            "Mr. Suit",
            "Strange",
            "Fragile",
            "Mannequin",
            "Different to Me",
            "Champs",
            "Feeling Called Love",
            "12XU",
        ],
    },
    {
        "artist": "Bauhaus",
        "album": "In the Flat Field",
        "year": "1980",
        "genre": "Goth",
        "tracks": [
            "Double Dare",
            "In the Flat Field",
            "A God in an Alcove",
            "Dive",
            "The Spy in the Cab",
            "Small Talk Stinks",
            "St. Vitus Dance",
            "Stigmata Martyr",
            "Nerves",
        ],
    },
    {
        "artist": "Talking Heads",
        "album": "Remain in Light",
        "year": "1980",
        "genre": "New Wave",
        "tracks": [
            "Born Under Punches (The Heat Goes On)",
            "Crosseyed and Painless",
            "The Great Curve",
            "Once in a Lifetime",
            "Houses in Motion",
            "Seen and Not Seen",
            "Listening Wind",
            "The Overload",
        ],
    },
    {
        "artist": "David Bowie",
        "album": "Low",
        "year": "1977",
        "genre": "Art Rock",
        "tracks": [
            "Speed of Life",
            "Breaking Glass",
            "What in the World",
            "Sound and Vision",
            "Always Crashing in the Same Car",
            "Be My Wife",
            "A New Career in a New Town",
            "Warszawa",
            "Art Decade",
            "Weeping Wall",
            "Subterraneans",
        ],
    },
    {
        "artist": "David Bowie",
        "album": "Heroes",
        "year": "1977",
        "genre": "Art Rock",
        "tracks": [
            "Beauty and the Beast",
            "Joe the Lion",
            "Heroes",
            "Sons of the Silent Age",
            "Blackout",
            "V-2 Schneider",
            "Sense of Doubt",
            "Moss Garden",
            "Neukoln",
            "The Secret Life of Arabia",
        ],
    },
    {
        "artist": "Kate Bush",
        "album": "Hounds of Love",
        "year": "1985",
        "genre": "Art Pop",
        "tracks": [
            "Running Up That Hill",
            "Hounds of Love",
            "The Big Sky",
            "Mother Stands for Comfort",
            "Cloudbusting",
            "And Dream of Sheep",
            "Under Ice",
            "Waking the Witch",
            "Watching You Without Me",
            "Jig of Life",
            "Hello Earth",
            "The Morning Fog",
        ],
    },
    {
        "artist": "Tangerine Dream",
        "album": "Phaedra",
        "year": "1974",
        "genre": "Electronic",
        "tracks": [
            "Phaedra",
            "Mysterious Semblance at the Strand of Nightmares",
            "Movements of a Visionary",
            "Sequent C'",
        ],
    },
    {
        "artist": "Klaus Schulze",
        "album": "Timewind",
        "year": "1975",
        "genre": "Electronic",
        "tracks": [
            "Bayreuth Return",
            "Wahnfried 1883",
        ],
    },
    {
        "artist": "Miles Davis",
        "album": "Bitches Brew",
        "year": "1970",
        "genre": "Jazz",
        "tracks": [
            "Pharaoh's Dance",
            "Bitches Brew",
            "Spanish Key",
            "John McLaughlin",
            "Miles Runs the Voodoo Down",
            "Sanctuary",
        ],
    },
    {
        "artist": "Miles Davis",
        "album": "Kind of Blue",
        "year": "1959",
        "genre": "Jazz",
        "tracks": [
            "So What",
            "Freddie Freeloader",
            "Blue in Green",
            "All Blues",
            "Flamenco Sketches",
        ],
    },
    {
        "artist": "John Coltrane",
        "album": "A Love Supreme",
        "year": "1965",
        "genre": "Jazz",
        "tracks": [
            "Acknowledgement",
            "Resolution",
            "Pursuance",
            "Psalm",
        ],
    },
    {
        "artist": "Alice Coltrane",
        "album": "Journey in Satchidananda",
        "year": "1971",
        "genre": "Jazz",
        "tracks": [
            "Journey in Satchidananda",
            "Shiva-Loka",
            "Stopover Bombay",
            "Something About John Coltrane",
            "Isis and Osiris",
        ],
    },
    {
        "artist": "Sigur Ros",
        "album": "Agaetis Byrjun",
        "year": "1999",
        "genre": "Post-Rock",
        "tracks": [
            "Intro",
            "Svefn-g-englar",
            "Staralfur",
            "Flugufrelsarinn",
            "Ny batteri",
            "Hjartad hamast",
            "Vidrar vel til loftarasa",
            "Olsen Olsen",
            "Agaetis byrjun",
            "Avalon",
        ],
    },
    {
        "artist": "Explosions in the Sky",
        "album": "The Earth Is Not a Cold Dead Place",
        "year": "2003",
        "genre": "Post-Rock",
        "tracks": [
            "First Breath After Coma",
            "The Only Moment We Were Alone",
            "Six Days at the Bottom of the Ocean",
            "Memorial",
            "Your Hand in Mine",
        ],
    },
    {
        "artist": "Tortoise",
        "album": "TNT",
        "year": "1998",
        "genre": "Post-Rock",
        "tracks": [
            "TNT",
            "Swung from the Gutters",
            "Ten-Day Interval",
            "I Set My Face to the Hillside",
            "The Equator",
            "A Simple Way to Go Faster Than Light That Does Not Work",
            "The Suspension Bridge at Iguazu Falls",
            "Four-Day Interval",
            "In Sarah, Mencken, Christ and Beethoven There Were Women and Men",
            "Almost Always Is Nearly Enough",
            "Jetty",
        ],
    },
    {
        "artist": "Fugazi",
        "album": "Repeater",
        "year": "1990",
        "genre": "Post-Hardcore",
        "tracks": [
            "Turnover",
            "Repeater",
            "Brendan #1",
            "Merchandise",
            "Blueprint",
            "Sieve-Fisted Find",
            "Greed",
            "Two Beats Off",
            "Styrofoam",
            "Reprovisional",
            "Shut the Door",
        ],
    },
    {
        "artist": "Slint",
        "album": "Spiderland",
        "year": "1991",
        "genre": "Post-Rock",
        "tracks": [
            "Breadcrumb Trail",
            "Nosferatu Man",
            "Don, Aman",
            "Washer",
            "For Dinner...",
            "Good Morning, Captain",
        ],
    },
    {
        "artist": "Pavement",
        "album": "Crooked Rain, Crooked Rain",
        "year": "1994",
        "genre": "Indie",
        "tracks": [
            "Silence Kit",
            "Elevate Me Later",
            "Stop Breathin",
            "Cut Your Hair",
            "Newark Wilder",
            "Unfair",
            "Gold Soundz",
            "5-4=Unity",
            "Range Life",
            "Heaven Is a Truck",
            "Hit the Plane Down",
            "Fillmore Jive",
        ],
    },
    {
        "artist": "Neutral Milk Hotel",
        "album": "In the Aeroplane Over the Sea",
        "year": "1998",
        "genre": "Indie",
        "tracks": [
            "The King of Carrot Flowers Pt. One",
            "The King of Carrot Flowers Pts. Two & Three",
            "In the Aeroplane Over the Sea",
            "Two-Headed Boy",
            "The Fool",
            "Holland, 1945",
            "Communist Daughter",
            "Oh Comely",
            "Ghost",
            "Untitled",
            "Two-Headed Boy Pt. Two",
        ],
    },
    {
        "artist": "Mazzy Star",
        "album": "So Tonight That I Might See",
        "year": "1993",
        "genre": "Dream Pop",
        "tracks": [
            "Fade into You",
            "Bells Ring",
            "Mary of Silence",
            "Five String Serenade",
            "Blue Light",
            "She's My Baby",
            "Unreflected",
            "Wasted",
            "Into Dust",
            "So Tonight That I Might See",
        ],
    },
    {
        "artist": "The Jesus and Mary Chain",
        "album": "Psychocandy",
        "year": "1985",
        "genre": "Noise Pop",
        "tracks": [
            "Just Like Honey",
            "The Living End",
            "Taste the Floor",
            "The Hardest Walk",
            "Cut Dead",
            "In a Hole",
            "Taste of Cindy",
            "Never Understand",
            "Inside Me",
            "Sowing Seeds",
            "My Little Underground",
            "You Trip Me Up",
            "Something's Wrong",
            "It's So Hard",
        ],
    },
]

os.makedirs(DEST, exist_ok=True)

count = 0
for album_info in ALBUMS:
    album_dir = os.path.join(DEST, album_info["artist"], album_info["album"])
    os.makedirs(album_dir, exist_ok=True)

    for i, title in enumerate(album_info["tracks"], 1):
        safe_title = title.replace("/", "-")
        fname = f"{i:02d} {safe_title}.mp3"
        fpath = os.path.join(album_dir, fname)
        shutil.copy2(SRC, fpath)

        tags = ID3()
        tags.add(TIT2(encoding=3, text=title))
        tags.add(TPE1(encoding=3, text=album_info["artist"]))
        tags.add(TPE2(encoding=3, text=album_info["artist"]))
        tags.add(TALB(encoding=3, text=album_info["album"]))
        tags.add(TRCK(encoding=3, text=f"{i}/{len(album_info['tracks'])}"))
        tags.add(TPOS(encoding=3, text="1/1"))
        tags.add(TDRC(encoding=3, text=album_info["year"]))
        tags.add(TCON(encoding=3, text=album_info["genre"]))
        tags.save(fpath)
        count += 1

print(f"Created {count} tracks across {len(ALBUMS)} albums in {DEST}")
